/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import modelo.Loxica.LoxicaCliente;
import modelo.Loxica.LoxicaPropietario;
import modelo.Loxica.LoxicaUsuario;
import modelo.dao.implementacion.concelloDAO.ConcelloDAO;
import modelo.vo.Concello.Concello;
import modelo.vo.Usuario.Cliente;
import modelo.vo.Usuario.Propietario;
import modelo.vo.Usuario.Usuario;
import org.apache.commons.codec.digest.DigestUtils;

import javax.swing.*;
import java.awt.event.WindowEvent;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;

/**
 * Clase que representa a interface na aplicación
 *
 * @author david
 */
public class DialogoRexistro extends javax.swing.JDialog {

    int xMouse, yMouse;
    private LoxicaUsuario loxicaUsuario = new LoxicaUsuario();
    private LoxicaPropietario loxicaPropietario = new LoxicaPropietario();
    private LoxicaCliente loxicaCliente = new LoxicaCliente();

    /**
     * Construtor de clase. Durante o inicio realiza conexións a bbdd
     * Creates new form DialogoRexistro
     */
    public DialogoRexistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        load();
        ComboRol.addItem("");
        ComboRol.addItem("Cliente");
        ComboRol.addItem("Propietario");

        ComboConcello.addItem("");
        ConcelloDAO concelloDAO = new ConcelloDAO();
        List<Concello> concellos = concelloDAO.read();
        for (Concello council : concellos
        ) {
            ComboConcello.addItem(String.valueOf(council.getNomeConcello()));
        }

    }
     private void load() {
        try {
            File file = new File("src/main/java/help/help.hs");
            URL hsURL = file.toURI().toURL();

            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            hb.enableHelpKey(this.rootPane.getContentPane(), "manual", helpset);

        } catch (MalformedURLException ex) {
            Logger.getLogger(LoadHelp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HelpSetException ex) {
            Logger.getLogger(LoadHelp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public DialogoRexistro() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        PanelEixe = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TextNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextApelido = new javax.swing.JTextField();
        TextApelido2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextRua = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextTelf = new javax.swing.JTextField();
        TextNum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ComboRol = new javax.swing.JComboBox<>();
        ComboConcello = new javax.swing.JComboBox<>();
        BotonGardar = new javax.swing.JButton();
        BotonBorrar = new javax.swing.JButton();
        BotonGardar1 = new javax.swing.JButton();
        TextContrasinal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelEixe.setBackground(new java.awt.Color(0, 72, 193));
        PanelEixe.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelEixeMouseDragged(evt);
            }
        });
        PanelEixe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelEixeMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("AXUDA -> F1");

        javax.swing.GroupLayout PanelEixeLayout = new javax.swing.GroupLayout(PanelEixe);
        PanelEixe.setLayout(PanelEixeLayout);
        PanelEixeLayout.setHorizontalGroup(
            PanelEixeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEixeLayout.createSequentialGroup()
                .addContainerGap(416, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        PanelEixeLayout.setVerticalGroup(
            PanelEixeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEixeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jPanel2.add(PanelEixe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 120));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 72, 193));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NOME");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 72, 193)));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 40));

        TextNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextNome.setForeground(new java.awt.Color(0, 72, 193));
        TextNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextNome.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 72, 193)));
        jPanel2.add(TextNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 340, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 72, 193));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("APELIDO1");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 72, 193)));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 90, 40));

        TextApelido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextApelido.setForeground(new java.awt.Color(0, 72, 193));
        TextApelido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextApelido.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 72, 193)));
        jPanel2.add(TextApelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 340, 40));

        TextApelido2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextApelido2.setForeground(new java.awt.Color(0, 72, 193));
        TextApelido2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextApelido2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 72, 193)));
        jPanel2.add(TextApelido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 340, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 72, 193));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("APELIDO2");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 72, 193)));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 90, 40));

        TextRua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextRua.setForeground(new java.awt.Color(0, 72, 193));
        TextRua.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextRua.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 72, 193)));
        jPanel2.add(TextRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 340, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 72, 193));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RUA");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 72, 193)));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 90, 40));

        TextEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextEmail.setForeground(new java.awt.Color(0, 72, 193));
        TextEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 72, 193)));
        jPanel2.add(TextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 340, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 72, 193));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PSWD");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 72, 193)));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 90, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 72, 193));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TELEFONO");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 72, 193)));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 90, 40));

        TextTelf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextTelf.setForeground(new java.awt.Color(0, 72, 193));
        TextTelf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextTelf.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 72, 193)));
        jPanel2.add(TextTelf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 110, 40));

        TextNum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextNum.setForeground(new java.awt.Color(0, 72, 193));
        TextNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextNum.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 72, 193)));
        jPanel2.add(TextNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 110, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 72, 193));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("N�");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 72, 193)));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 90, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 72, 193));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CONCELLO");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 72, 193)));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 90, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 72, 193));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ROL");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 72, 193)));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 90, 40));

        ComboRol.setBackground(new java.awt.Color(0, 72, 193));
        ComboRol.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(ComboRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 110, 40));

        ComboConcello.setBackground(new java.awt.Color(0, 72, 193));
        ComboConcello.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(ComboConcello, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 110, 40));

        BotonGardar.setBackground(new java.awt.Color(102, 102, 255));
        BotonGardar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonGardar.setForeground(new java.awt.Color(255, 255, 255));
        BotonGardar.setText("GARDAR");
        BotonGardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGardarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonGardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 140, 50));

        BotonBorrar.setBackground(new java.awt.Color(102, 102, 255));
        BotonBorrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonBorrar.setForeground(new java.awt.Color(255, 255, 255));
        BotonBorrar.setText("CANCELAR");
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 140, 50));

        BotonGardar1.setBackground(new java.awt.Color(102, 102, 255));
        BotonGardar1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonGardar1.setForeground(new java.awt.Color(255, 255, 255));
        BotonGardar1.setText("BORRAR");
        BotonGardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGardar1ActionPerformed(evt);
            }
        });
        jPanel2.add(BotonGardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 140, 50));

        TextContrasinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextContrasinal.setForeground(new java.awt.Color(0, 72, 193));
        TextContrasinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextContrasinal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 72, 193)));
        jPanel2.add(TextContrasinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 340, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 72, 193));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("EMAIL");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 72, 193)));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 90, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método void para a limpexa dos cadros de texto
     */
    public void clean() {
        TextNome.setText(null);
        TextApelido.setText(null);
        TextApelido2.setText(null);
        ComboConcello.setSelectedIndex(0);
        TextRua.setText(null);
        TextNum.setText(null);
        TextTelf.setText(null);
        TextEmail.setText(null);
        ComboRol.setSelectedIndex(0);
        TextContrasinal.setText(null);
    }

    /**
     * Método para control da ubicación da interface en pantalla
     *
     * @param evt
     */
    private void PanelEixeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEixeMousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();

        // TODO add your handling code here:
    }//GEN-LAST:event_PanelEixeMousePressed

    /**
     * Método para control da ubicación da interface en pantalla
     *
     * @param evt
     */
    private void PanelEixeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEixeMouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelEixeMouseDragged

    /**
     * Método para a creación e gardado de usuario na bbdd
     *
     * @param evt
     */
    private void BotonGardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGardarActionPerformed
        try {
            String nome = TextNome.getText();
            String apelido1 = TextApelido.getText();
            String apelido2 = TextApelido2.getText();
            String rua = TextRua.getText();
            String concelloText = String.valueOf(ComboConcello.getSelectedItem());
            int num = Integer.parseInt(TextNum.getText().replaceAll("\\p{Punct}", ""));
            String telefono = TextTelf.getText().replaceAll("\\p{Punct}", "");
            String email = TextEmail.getText();
            String contrasinal = DigestUtils.md5Hex(String.valueOf(TextContrasinal.getText()));
            //String contrasinal = TextContrasinal.getText();
            String rol = String.valueOf(ComboRol.getSelectedItem());

            if (!rol.isEmpty() && !rol.isBlank()) {
                if (checkStringData(nome)
                        && checkStringData(apelido1)
                        && checkStringData(apelido2)
                        && checkStringData(rua)) {
                    if (rol.equals("Cliente")) {
                        Usuario usuarioCli = new Cliente();
                        if (!nome.isEmpty() && !nome.isBlank() && nome.length() >= 3 &&
                                !apelido1.isEmpty() && !apelido1.isBlank() && !apelido2.isBlank() && !apelido2.isEmpty() && !rua.isEmpty() && !rua.isBlank()
                                && !concelloText.isBlank() && !concelloText.isEmpty() && num > 0 && !telefono.isEmpty() && !telefono.isBlank()
                                && !email.isBlank() && !email.isEmpty() && !contrasinal.isEmpty() && !contrasinal.isBlank() && contrasinal.length() >= 3) {
                            usuarioCli.setNome(nome);
                            usuarioCli.setApelido1(apelido1);
                            usuarioCli.setApelido2(apelido2);
                            usuarioCli.setRua(rua);
                            String concello = concelloText;
                            Concello council = new Concello();
                            council.setNomeConcello(concello);
                            usuarioCli.setConcello(council);
                            usuarioCli.setNumero(num);
                            usuarioCli.setTelefono(telefono);
                            usuarioCli.setEmail(email);
                            usuarioCli.setContrasinal(contrasinal);
                            usuarioCli.setRol(rol);
                            loxicaUsuario.validarCreateUsuario(usuarioCli);
                            loxicaCliente.validarCreateCliente(usuarioCli);
                            clean();
                        } else {
                            JOptionPane.showMessageDialog(null, "Datos introducidos non válidos");
                        }
                    } else if (rol.equals("Propietario")) {
                        Usuario usuarioPro = new Propietario();
                        if (!nome.isEmpty() && !nome.isBlank() && nome.length() >= 3 &&
                                !apelido1.isEmpty() && !apelido1.isBlank() && !apelido2.isBlank() && !apelido2.isEmpty() && !rua.isEmpty() && !rua.isBlank()
                                && !concelloText.isBlank() && !concelloText.isEmpty() && num > 0 && !telefono.isEmpty() && !telefono.isBlank()
                                && !email.isBlank() && !email.isEmpty() && !contrasinal.isEmpty() && !contrasinal.isBlank() && contrasinal.length() >= 3) {
                            usuarioPro.setNome(nome);
                            usuarioPro.setApelido1(apelido1);
                            usuarioPro.setApelido2(apelido2);
                            usuarioPro.setRua(rua);
                            String concello = concelloText;
                            Concello council = new Concello();
                            council.setNomeConcello(concello);
                            usuarioPro.setConcello(council);
                            usuarioPro.setNumero(num);
                            usuarioPro.setTelefono(telefono);
                            usuarioPro.setEmail(email);
                            usuarioPro.setContrasinal(contrasinal);
                            usuarioPro.setRol(rol);
                            loxicaUsuario.validarCreateUsuario(usuarioPro);
                            loxicaPropietario.validarCreatePropietario(usuarioPro);
                            clean();
                        } else {
                            JOptionPane.showMessageDialog(null, "Datos introducidos non válidos");
                            JOptionPane.showMessageDialog(null, "RECORDA: NOME MIN 3 CARACTERES");
                            JOptionPane.showMessageDialog(null, "RECORDA: PWD MIN 3 CARACTERES");


                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Introduce unicamente letras", "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecciona un rol");

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error rexistrando datos", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_BotonGardarActionPerformed

    public static boolean checkStringData(String numberCheck) {
        int number = 999;
        char[] nieCharacterers = numberCheck.toCharArray();
        for (char c : nieCharacterers) {
            if (Character.isLetter(c)) {
                number++;
            }
        }
        return !numberCheck.isEmpty() &&
                (nieCharacterers.length != 999 && number == nieCharacterers.length + 999);
    }

    /**
     * Método para cerrar a ventá ao pulsar o botón
     *
     * @param evt
     */
    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed

        this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));

    }//GEN-LAST:event_BotonBorrarActionPerformed

    /**
     * Método que chama ao método clean e o executa ao pulsar o botón
     *
     * @param evt
     */
    private void BotonGardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGardar1ActionPerformed

        clean();
    }//GEN-LAST:event_BotonGardar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoRexistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoRexistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoRexistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoRexistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        FlatIntelliJLaf.setup();
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoRexistro dialog = new DialogoRexistro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonGardar;
    private javax.swing.JButton BotonGardar1;
    private javax.swing.JComboBox<String> ComboConcello;
    private javax.swing.JComboBox<String> ComboRol;
    private javax.swing.JPanel PanelEixe;
    private javax.swing.JTextField TextApelido;
    private javax.swing.JTextField TextApelido2;
    private javax.swing.JTextField TextContrasinal;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextNome;
    private javax.swing.JTextField TextNum;
    private javax.swing.JTextField TextRua;
    private javax.swing.JTextField TextTelf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
