/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Xanelas;

import modelo.vo.Local.Local;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author david
 */
public class Busqueda extends javax.swing.JPanel {

    /**
     * Creates new form Busqueda
     */
    public Busqueda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboConcelloBusc = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        ComboTipoLocalBusc = new javax.swing.JComboBox<>();
        botonBuscarLocal = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setMinimumSize(new java.awt.Dimension(480, 60));
        setPreferredSize(new java.awt.Dimension(580, 130));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PRODUCTO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 90, 30));

        jLabel2.setText("TIPO DE SERVIZO");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 120, 30));

        jLabel3.setText("CONCELLO");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 100, 30));

        ComboConcelloBusc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(ComboConcelloBusc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 90, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 80, -1));

        ComboTipoLocalBusc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(ComboTipoLocalBusc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 100, -1));

        botonBuscarLocal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonBuscarLocal.setForeground(new java.awt.Color(0, 72, 193));
        botonBuscarLocal.setText("DALLE");
        botonBuscarLocal.setPreferredSize(new java.awt.Dimension(51, 25));
        botonBuscarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarLocalActionPerformed(evt);
            }
        });
        add(botonBuscarLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 5, 84, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarLocalActionPerformed

        List<Local> locais = new ArrayList<>();
        for (Local local: locais
             ) {
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarLocalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboConcelloBusc;
    private javax.swing.JComboBox<String> ComboTipoLocalBusc;
    private javax.swing.JButton botonBuscarLocal;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
